In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
df = pd.read_csv('Datasets/glass.csv')
df.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [3]:
X = df.drop('Type',axis=1)
y = df.Type

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 111)

In [5]:
from sklearn.svm import SVC

model1 = SVC(kernel = 'sigmoid')
model2 = SVC(kernel = 'poly')
model3 = SVC(kernel = 'rbf')

In [6]:
model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

SVC()

In [7]:
y_pred1 = model1.predict(X_test)
y_pred2 = model2.predict(X_test)
y_pred3 = model3.predict(X_test)

In [8]:
print("Evaluation of Model 1 Sigmoid: ")
print(confusion_matrix(y_test, y_pred1))
print(classification_report(y_test, y_pred1))

Evaluation of Model 1 Sigmoid: 
[[12  3  0  0  0]
 [ 0 14  0  0  0]
 [ 0  5  0  0  0]
 [ 0  4  0  0  0]
 [ 0  5  0  0  0]]
              precision    recall  f1-score   support

           1       1.00      0.80      0.89        15
           2       0.45      1.00      0.62        14
           3       0.00      0.00      0.00         5
           5       0.00      0.00      0.00         4
           7       0.00      0.00      0.00         5

    accuracy                           0.60        43
   macro avg       0.29      0.36      0.30        43
weighted avg       0.50      0.60      0.51        43



C:\Users\srira\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\srira\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\srira\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [9]:
print("Evaluation of Model 2 Polynomial: ")
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

Evaluation of Model 2 Polynomial: 
[[15  0  0  0  0  0]
 [ 1 13  0  0  0  0]
 [ 0  1  4  0  0  0]
 [ 0  0  0  2  2  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  5]]
              precision    recall  f1-score   support

           1       0.94      1.00      0.97        15
           2       0.93      0.93      0.93        14
           3       1.00      0.80      0.89         5
           5       1.00      0.50      0.67         4
           6       0.00      0.00      0.00         0
           7       1.00      1.00      1.00         5

    accuracy                           0.91        43
   macro avg       0.81      0.70      0.74        43
weighted avg       0.95      0.91      0.92        43



C:\Users\srira\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\srira\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\srira\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [10]:
print("Evaluation of Model 3 RBF: ")
print(confusion_matrix(y_test, y_pred3))
print(classification_report(y_test, y_pred3))

Evaluation of Model 3 RBF: 
[[15  0  0  0  0]
 [ 0 14  0  0  0]
 [ 0  5  0  0  0]
 [ 0  0  2  0  2]
 [ 0  0  0  0  5]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        15
           2       0.74      1.00      0.85        14
           3       0.00      0.00      0.00         5
           5       0.00      0.00      0.00         4
           7       0.71      1.00      0.83         5

    accuracy                           0.79        43
   macro avg       0.49      0.60      0.54        43
weighted avg       0.67      0.79      0.72        43



C:\Users\srira\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\srira\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\srira\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
